### ISSUE TITLE
Update terraform version and jenkins-plugin-cli

### ISSUE THREAD

**Issue by riwiki** [aws-samples/serverless-jenkins-on-aws-fargate#11]
Hi there,

is this sample project still maintained and are pull-requests welcomed and checked? If so, I am happy to provide an update on the mentioned issues. At the moment, an outdated terraform version is used, as well as the deprecated install-plugins.sh script which will be replaced by the jenkins-plugin-cli.

Cheers,
Richard

**Comment by edjumacator** [comment]
I'm having issues deploying the example, I've created the required prerequisites prior to executing it, and then I've properly changed the vars.sh file to use the newly created parameters but while executing the script I'm getting an error on the docker deployment step 

```
│ Error: local-exec provisioner error
│
│   with module.serverless_jenkins.null_resource.build_docker_image,
│   on ../modules/jenkins_platform/jenkins_image.tf line 54, in resource "null_resource" "build_docker_image":
│   54:   provisioner "local-exec" {
│
│ Error running command 'docker login -u AWS -p
│ // Key is here but I removed for this issue 
│ 037395434333.dkr.ecr.us-west-1.amazonaws.com && \
│ docker build -t 037395434333.dkr.ecr.us-west-1.amazonaws.com/serverless-jenkins-controller:latest ../modules/jenkins_platform/docker/ && \
│ docker push 037395434333.dkr.ecr.us-west-1.amazonaws.com/serverless-jenkins-controller:latest
│ ': exit status 1. Output: WARNING! Using --password via the CLI is insecure. Use --password-stdin.
│ Login Succeeded
│ Command "build" not available in current context (jenkins), you can use the "default" context to run this command
```

Then in the tear down process described by the AWS Documentation I'm getting an error that points to a VPC ID that I did not provide in my vars.sh file 

``` 
╷
│ Error: InvalidVpcID.NotFound: The vpc ID 'vpc-0a7d01e2f13b6cc16' does not exist
│ 	status code: 400, request id: d976b08f-d047-4d9b-abca-a78abb73803d
│
│   with module.serverless_jenkins.data.aws_vpc.selected,
│   on ../modules/jenkins_platform/main.tf line 4, in data "aws_vpc" "selected":
│    4: data "aws_vpc" selected {
│
╵
```

Have (or did) you experience these issues while deploying this example? I'll create an issue on my own if not but I wanted to check with you given that you created this issue a few hours ago.

**Comment by krithivasan** [comment]
@riwiki please feel free to submit a PR.

**Comment by apogorielov** [comment]
Hi @riwiki, thank you for the pointer to deprecated functionality.  We have pushed the fix for this issue in the PR above
