### ISSUE TITLE
Agents deployed to ALB subnet?  

### ISSUE THREAD

**Issue by joshuaganger** [aws-samples/serverless-jenkins-on-aws-fargate#13]
On line 30 of jenkins_image.tf this lne:

` subnets                   = join(",", var.alb_subnet_ids)`

appears to configure agents to deploy into the public subnet of the ALB.  The diagram here: https://aws.amazon.com/blogs/devops/building-a-serverless-jenkins-environment-on-aws-fargate/ shows agents deploying into private subnets.  

Should this line use var.jenkins_controller_subnet_ids or am I misunderstanding the purpose of this section?

**Comment by apogorielov** [comment]
Hi @joshuaganger, thank you for the hint! We have pushed the fix for this issue.
