### ISSUE TITLE
Is this setup applicable to multi account ?

### ISSUE THREAD

**Issue by kishoremarojuu** [aws-samples/serverless-jenkins-on-aws-fargate#17]
Hi, can we get this done for the multi account setup ? 
I am trying to host Jenkins master node in account-A and slave nodes in account-b and account-c 

1. How do we connect slave nodes to master nodes ? Can we get this done using this terraform code ? 

Thanks in advance.

**Comment by moitrasayan007** [comment]
Hi,

This is possible to launch jenkins master in one account and launch the fargate spot/fargate agents in another account using cross account iam role for the jenkins master to trigger ecs fargate creation. I haven't tried this myself, we use it in our infra which does the setup in same account.

But it is possible, you can give this a try.

**Comment by apogorielov** [comment]
Hi, 
With several updates to the terraform code it is possible to convert this deployment to multi account setup, but unfortunately we don't have any plans yet on  providing such functionality.
