### ISSUE TITLE
Are gid and uid reversed?

### ISSUE THREAD

**Issue by stewberg** [aws-samples/serverless-jenkins-on-aws-fargate#20]
https://github.com/aws-samples/serverless-jenkins-on-aws-fargate/blob/6f0969ff4c0a90673792ce75161fe976c29c7768/modules/jenkins_platform/efs.tf#L31

**Comment by apogorielov** [comment]
Hi @stewberg,
Thank you for pointing this out. Since the UID and GID had same value this did not affect anything this stage, but we did in fact fixed this in #21.

Kind regards,
Alex
