### ISSUE TITLE
list of policy

### ISSUE THREAD

**Issue by gabriel-tessier** [aws-samples/serverless-jenkins-on-aws-fargate#22]
Hi,
Is there a way to have the list of all the policy to apply to the user who deploy. I didn't find anything related to this in the readme or in the source files.
Any help is welcome.

Thanks.

**Comment by apogorielov** [comment]
Hi, 
Unfortunately we don't have the minimal policy available. 
We will try to provide this as a part of documentation in the upcoming updates.
