### ISSUE TITLE
update dockerfile and plugins

### ISSUE THREAD

**Issue by azerioglan** [aws-samples/serverless-jenkins-on-aws-fargate#23]
Hello guys,
I used your code to bring up fargate cluster. didn't find options to update docker image or list of plugins deployed first time. 
Documentation refers that need to create new task definition. But didn't figure out how to handle in code. simple deploy.sh diddn't help
Appreciate for help or for directions

Thanks.

**Comment by apogorielov** [comment]
I've added trigger to the the main code to automatically rebuild instances, as well as list of updated plugins. Therefor I am closing this issue.
