### ISSUE TITLE
Builds are stuck waiting to connect to agents

### ISSUE THREAD

**Issue by ghost** [aws-samples/serverless-jenkins-on-aws-fargate#24]
Tried to run simple job critical task and got this in the agent log:

ECS: Launching agent
Waiting for agent to start: fargate-cloud-simple-job-critical-task-1-c0z77-kpczx
Waiting for agent to connect: fargate-cloud-simple-job-critical-task-1-c0z77-kpczx
Waiting for agent to connect: fargate-cloud-simple-job-critical-task-1-c0z77-kpczx
Waiting for agent to connect: fargate-cloud-simple-job-critical-task-1-c0z77-kpczx

**Comment by devy294** [comment]
any update on this? Running into the same issue. I think it may have something to do with the Tunneling settings

**Comment by apogorielov** [comment]
Hi! Unfortunately I would need a bit more information to help you address this issue.
Please try to use latest updates from the main branch with up to date plugins and configuration.
If this issue persist I would kindly ask to provide information if the workers ECS Task were spawned and logs from those instances.
