### ISSUE TITLE
After deploy not able connect with ALB DNS name

### ISSUE THREAD

**Issue by aMfM9E2** [aws-samples/serverless-jenkins-on-aws-fargate#9]
I can see all deployment are in green stage but not allow connect with  ALB DNS name

**Comment by apogorielov** [comment]
Hi @aMfM9E2, 

Unfortunately to assist you further we would need a bit more details. 
Would it be possible to get the logs from ECS Fargate that could indicate why it isn't ?

Kind regards,
Alex

**Comment by apogorielov** [comment]
Closing this issue since the module was successfully tested as part of last PR
